name: Build and Release Android APK

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build-android:
    name: 📱 Android APK Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Set up Java 17 instead of Java 11
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '17'  # Update to Java 17

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - run: flutter pub get
      - run: flutter build apk --release --split-per-abi

      - name: Upload Android APK to Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/app/outputs/apk/release/*.apk
          tag: v0.0.1
          overwrite: true
          body: "This is the first Android release"
